### ISSUE TITLE
Doc Request

### ISSUE THREAD

**Issue by zhongyi-tong** [starkwang/XKHelper#1]
能给个doc或者screen shot吗。。从README看不出这有什么功能

**Comment by starkwang** [comment]
这是新版选课助手的源码，具体网址在：
http://stu.fudan.edu.cn/xk/

doc的话，可以看我的博客：
http://blog.starkwang.com/2015/10/17/xkhelper/

**Comment by starkwang** [comment]
现在的课程数据还是这个学期的（而且不完全），等12月下学期的课表出来了，新选课助手应该会正式启用。

**Comment by zhongyi-tong** [comment]
哦哦是这个，还以为是抢课的……
